name: wstkde
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - numba>=0.60.0
  - numpy>=2.0.2
  - scipy>=1.7
  - pandas>=2.2.3
  - geopandas>=1.0.1
  - pyvista>=0.44.1

# optional_dependencies:
#   - ipykernel>=6.29.5  # Optional dependency for running notebooks
#   - matplotlib>=3.9.2  # Optional dependency for plotting in notebooks
#   - pyarrow>=17.0.0    # Optional dependency for reading parquet files
